### PR TITLE
Added support for Windows, with Clang + MSVC

### PR DESCRIPTION
**Pull request by clibequilibrium**
This PR adds support for Windows, using Clang compiler & linkage to MSVC. 

I also had some issue with export symbols ` __declspec(dllexport)` . Otherwise it worked without a problem on Windows platform.  

Thank you for this work !

### CODE REVIEW

**Comment by clibequilibrium** [comment]
Found an issue with carriage return. Closing for now and will re-add the PR

**Comment by clibequilibrium** [comment]
Reopening for CR/LF characters

**Comment by Isty001** [comment]
Thank you for this! Could you maybe extend `.github/workflows/test.yml` with a `windows` job? It'd be cool to know in the future that the compatibility is not broken accidentally.

**Comment by clibequilibrium** [comment]
> Thank you for this! Could you maybe extend `.github/workflows/test.yml` with a `windows` job? It'd be cool to know in the future that the compatibility is not broken accidentally. 

Great idea! I will do that and update the PR!

**Comment by clibequilibrium** [comment]
@Isty001  I added windows-latest support with MSVC build step.
Please note I had to take advantage of CTest so Makefile is not actually used anymore to build tests, but rather CMakeLists. 

Also dotenv.c had non constant array allocation which is not supported on MSVC i.e  `char str[strlen("Hello")]` it only supports constant array sizes like `char str[512]`.
 
I also took advantage of copying final env files for test via

`configure_file(test/.env ${CMAKE_BINARY_DIR}/test/.env COPYONLY)`
`configure_file(test/.test.env ${CMAKE_BINARY_DIR}/test/.test.env COPYONLY)`
 
Let me know what you think ! Crucial changes are in test.yml, CMakeLists.txt and dotenv.c
And here is the successful CI on my [fork](https://github.com/clibequilibrium/dotenv-c/actions/runs/3802253816)

**Comment by Isty001** [comment]
Thank you!

**Pull request merged**
